version: '3.4'
services:
  service-db:
    image: postgres:15
    environment:
      POSTGRES_USER: kek
      POSTGRES_PASSWORD: kek
      POSTGRESS_DB: kek
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  web:
      build: .
      depends_on:
        service-db:
          condition: service_healthy
      ports:
        - "8000:8000"