version: '3.4'
services:
  postgres:
    image: postgres:15
    expose:
      - 5432
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRESS_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  web:
      build: .
      depends_on:
        postgres:
          condition: service_healthy
      ports:
        - "8000:8000"