version: '3'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "0.0.0.0:8000:8000"
  db:
    image: postgres:15
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRESS_DB: postgres